---
-  hosts: all
   become: true
   tasks: 
   -  name: install apache2 package
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == "CentOS"

   -  name: update packages
      yum:
        update_cache: yes
      when: ansible_distribution_version == "9"    
