---
-  hosts: all
   become: true
   pre_tasks:
     -  name: Update repo
        tags: always
        dnf:
          update_cache: yes
        changed_when: false
        when: ansible_distribution == "CentOS"

-  hosts: all
   become: true
   roles:
     -  base

-  hosts: web_servers
   become: true
   roles:
     -  web_servers

-  hosts: db_servers
   become: true
   roles:
     -  db_servers

-  hosts: workstations
   become: true
   roles:
     -  workstations

-  hosts: file_servers
   become: true
   roles:
     -  file_servers  
