---
-  hosts: all
   become: true  
   pre_tasks:
   -  name: check updates (Centos)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
        state: latest
      when: ansible_distribution == "CentOS"

   -  name: check updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
        state: latest
      when: ansible_distribution == "Ubuntu"

-  hosts: [workstations]
   become: true
   tasks:
   -  name: Install  unzip
      package:
        name: unzip
   -  name: Install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes  
        mode: 0644
        owner: root
        group: root


-  hosts: web_servers
   become: true
   tasks:
   -  name: install httpd package
      tags: centos,apache,httpd
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"

   -  name: copy html file
      tags: httpd,apache,centos
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644     

-  hosts: file_servers
   become: true
   tasks:
   -  name: Install samba package
      tags: samba,file_server
      package:
        name: samba
        state: latest 

-  hosts: db_servers
   become: true
   tasks:
   -  name: Install MariaDB on centos
      tags: db,centos,centos
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"    
           
