-   name: Install  unzip
    package:
    name: unzip

-   name: Install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes  
      mode: 0644
      owner: root
      group: root
